name: example
version: 1.0.0
homepage: https://github.com/eppeque/animated_headline

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  animated_headline:

dev_dependencies:
  flutter_test:
    sdk: flutter
  
dependency_overrides:
  animated_headline:
    path: ../

flutter:
  uses-material-design: true